config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root 'logo#index'

  get "logo" => 'logo#index'
  get "logo/library" => 'logo#library'
  get "logo/library/editor/:library_logo_id" => 'logo#library_editor'
  get "logo/bonus", to: 'logo#bonus'
  post "logo/shared/save", to: "logo#import_from_library"
  post "logo/bonus/save", to: "logo#import_from_bonus"
  get "logo/new" => 'logo#new'
  get "edit/:user_logo_id", to: 'logo#edit_logo'
  get 'embed_raster_to_svg', to: 'logo#embed_raster_to_svg'
  post '/import/store_raster', to: 'logo#store_raster'
  get "logo/editor" => 'logo#editor'
  get "logo/clone" => 'logo#clone'
  post "logo/duplicate", to: 'logo#clone_user_logo'
  post "logo/save", to: 'logo#save'
  post "logo/update", to: 'logo#update_user_logo'
  get "logo/delete", to: 'logo#delete_user_logo'
  post "logo/delete", to: 'logo#ajax_delete_user_logo'
  get "logo/:logo_id/as/file", to: 'logo#as_file'
  get "user/logo/:logo_id/as/file", to: 'logo#user_logo_as_file'
  get "shared/logo/:logo_id/as/file", to: 'logo#shared_logo_as_file'
  get "logo/categories/list", to: 'logo#categories_list'
  get "logo/:logo_id/json", to: 'logo#as_json'
  get "logo/:category_id/set", to: 'logo#symbols_set'
  post "logo/share", to: 'logo#share_logo'
  post "import/logo", to: 'logo#clone'
  post "logo/svg", to: 'logo#get_svg'

  get "export/raster/:file_type/:logo_id/:size", to: 'logo#svg_to_raster'

  get "experimental", to: 'experimental#index'
  get "raster_to_svg", to: 'experimental#raster_to_svg'
  get "svg_to_raster", to: 'experimental#svg_to_raster'
  get "svg_to_psd", to: 'experimental#svg_to_psd'
  post "logo/ocr", to: 'experimental#logo_ocr'

  get "import/logo/page", to: 'logo#get_page'
  post "import/logo/page", to: 'logo#get_page'

  get "logo/openclipart_download", to: 'logo#openclipart_download'

  get "color/palettes", to: 'logo#get_palettes'
  get "layouts/list", to: 'logo#get_layouts'
  get "all/colors", to: 'logo#all_colors'
  get "all/palettes", to: 'logo#all_palettes'

  post 'accounts/zaxaa', to: "welcome#zaxaa_zpn"
  match 'accounts/zaxaa', to: 'welcome#zaxaa_zpn', :constraints => { :protocol => 'https' }, :via => :get

  post 'accounts/jvz', to: "welcome#jvzoo"
  match 'accounts/jvz', to: 'welcome#jvzoo', :constraints => { :protocol => 'https' }, :via => :get
  
  get 'help', to: "help_videos#index"
end

app/models/layout.rb
class Layout < ActiveRecord::Base
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixxly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" charset="utf-8">
    var browser = "<%= browser.name %>";
  </script>
</head>
<body onload="initialize();">
  <div class="container">
    <a href="index.html">
      <%= image_tag "pixxly-logo.png", style: "height: 100px;" %>
    </a>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "<i class='fa fa-picture-o'></i>&nbsp;My Logos".html_safe, logo_path %></li>
            <%- # If there is no expires_on date for the user, compare today to tomorrow. -%>
            <%- expires = current_user.expires_on || Date.today + 1.day -%>
            <%- unless expires < Date.today -%>
            <li><%= link_to "<i class='fa fa-book'></i>&nbsp;Library".html_safe, logo_library_path %></li>
            <li><%= link_to "<i class='fa fa-plus-square-o'></i>&nbsp;New Logo".html_safe, logo_new_path %></li>
            <li><a href="#" data-target="#cloneLogoSourceModal" data-toggle="modal"><i class='fa fa-clone'></i>&nbsp;Clone Logo</a></li>
            <%- end -%>
            <li><a href="#" data-target="#installBonusLogosModal" data-toggle="modal" id="launch_logo_import_modal"><i class="fa fa-folder-open-o"></i>&nbsp;Pixxly Logo Import</a></li>

            <% if current_user.bonus? %>
            <li><%= link_to "<i class='fa fa-certificate'></i>&nbsp;Bonus Logos".html_safe, logo_bonus_path %></li>
            <% end %>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li title="Help & Tutorials"><%= link_to help_path do %>
              <span class="fa fa-question-circle"></span>
            <% end %></li>
            <li title="Log out"><%= link_to destroy_user_session_path, method: :delete do %>
              <span class="fa fa-sign-out"></span>
            <% end %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= render "logo/ie_warning" if (browser.ie? || browser.edge?) %>
    <%= yield %>
  </div>

  <!-- Modals -->
  <!-- Clone logo source modal. -->
  <div class="modal fade" id="cloneLogoSourceModal" tabindex="-1" role="dialog" aria-labelledby="cloneLogoSourceLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="cloneLogoSource">Clone a logo</h4>
        </div>
        <div class="modal-body">
          <label for="">Image URL:</label>
          <input style="display: inline; width: 85%;" type="text" class="form-control" name="page_url" id="page_url" placeholder="http://www.example.com/logo.jpg" /><small>Make sure your link is for a .jpg, .png, or .gif.</small>
          <div style="text-align: center;"><label style="margin-top: 20px" style="left:50%" for="">or</label></div>
          <div id="images_from_site" style="display: flex; justify-content: center; flex-wrap: wrap; flex-flow: wrap; align-items: center;"></div>
          <div style="margin-top: 20px; margin-bottom: 20px">
            <label for="">Choose a File:</label>
            <input style="display: inline; width: 68%;" type="text" class="form-control" name="page_path" id="page_path" placeholder="c:\logo.jpg" readonly/>
            <label style="display: inline;" class="btn btn-primary" for="button_for_open_file">Open...</label>
            <input id="button_for_open_file" type="file" style="display:none;">
          </div>
          <small>Do you have a template logo that you want to use? Pixxly can attempt to convert it to a highly flexible format, or embed it exactly as it is.</small>
          <br>

          <!--<input id="convert_to_svg_checkbox" value="true" type="hidden">-->
          <!--<button class="btn btn-primary convert-or-embed convert-choice-active" data-convert="true">Convert to Scalable Image</button>-->
          <!--<button class="btn btn-primary convert-or-embed" data-convert="false">Embed Image As It Is</button>-->

          <div class="btn-group btn-group-justified" data-toggle="buttons">
            <label class="btn btn-primary active">
              <input type="radio" name="convert-or-embed" autocomplete="off" data-convert="true" value="import_svg" checked>Scalable Import
            </label>
            <label class="btn btn-primary">
              <input type="radio" name="convert-or-embed" data-convert="false" autocomplete="off" value="embed_raster">Normal Image Import
            </label>
            <input id="convert_to_svg_checkbox" value="true" type="hidden">
          </div>

          <br>

          <!--<div class="btn-group btn-group-justified" data-toggle="buttons" id="black_and_white_toggle">-->
            <!--<label class="btn btn-primary active">-->
              <!--<input type="radio" name="inlineRadioOptions" id="image_is_black_and_white" autocomplete="off" checked>Logo Outline Only-->
            <!--</label>-->
            <!--&lt;!&ndash;<label class="btn btn-primary">&ndash;&gt;-->
              <!--&lt;!&ndash;<input type="radio" name="inlineRadioOptions" id="image_is_color" autocomplete="off">Full Color Import&ndash;&gt;-->
            <!--&lt;!&ndash;</label>&ndash;&gt;-->
            <!--<input type="hidden" name="inlineRadioOptions" id="image_is_black_and_white" value=false />-->
          <!--</div>-->

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary btn-clone-logo">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End clone logo source modal. -->

  <!-- Install bonus logos modal. -->
  <div class="modal fade" id="installBonusLogosModal" tabindex="-1" role="dialog" aria-labelledby="installBonusLogosLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="cloneLogoSource"><i class="fa fa-upload"></i>&nbsp;Import Pixxly Logos</h4>
        </div>
        <div class="modal-body">
          <p>Choose the .svg file you wish to import:</p>

          <div style="margin-top: 20px; margin-bottom: 20px">
            <label for="">Choose a File:</label>
            <input style="display: inline; width: 68%;" type="text" class="form-control" name="bonus_path" id="bonus_path" placeholder="c:\pixxly_bonus_logo.svg" readonly/>
            <label style="display: inline;" class="btn btn-primary" for="button_for_import_files">Open...</label>
            <input id="button_for_import_files" type="file" style="display:none;" accept="image/svg+xml, .svg">
          </div>
          <!-- Progress bar. -->
          <div class="progress" id="bonus_upload_progress_div" style="display: none;">
            <div class="progress-bar progress-bar-success progress-bar-striped" id="bonus_upload_progress" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
              <span class="sr-only">40% Complete (success)</span>
            </div>
          </div>
          <!-- End progress bar. -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End install bonus logos modal. -->
  <!-- End modals. -->

  <footer class="footer">
    <div class="container">
      <p class="text-muted">&copy; <%= Time.new.year %>. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>

app/views/layouts/user_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixxly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>